### ISSUE TITLE
Problem trying to set the color of the LightBlue Bean

### ISSUE THREAD

**Issue by kdious** [octoblu/meshblu-connector-bean#2]
Steps to repro:
1. Install a Lightblue Bean connector on my Mac OS X machine
2. Use a trigger in the Octoblu flow to trigger the Bean to try and change the color (I used "red")

It looks as if the connector stops and then restarts automatically.

Bean connector error:

Errors from a minute ago
Sat, 23 Jul 2016 22:38:20 GMT meshblu-connector-bean:index started
Sat, 23 Jul 2016 22:38:20 GMT meshblu-connector-bean:index on config { interval: { accelerometer: 0, rssi: 0, temperature: 0 },
localName: 'KD-Bean',
notify:
{ scratch1: false,
scratch2: false,
scratch3: false,
scratch4: false,
scratch5: false } }
Sat, 23 Jul 2016 22:38:25 GMT meshblu-connector-bean:index on config { interval: { accelerometer: 0, rssi: 0, temperature: 0 },
localName: 'KD-Bean',
notify:
{ scratch1: false,
scratch2: false,
scratch3: false,
scratch4: false,
scratch5: false } }
Sat, 23 Jul 2016 22:38:27 GMT meshblu-connector-bean:index on config { interval: { accelerometer: 0, rssi: 0, temperature: 0 },
localName: 'KD-Bean',
notify:
{ scratch1: false,
scratch2: false,
scratch3: false,
scratch4: false,
scratch5: false } }
/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/src/bean-manager.coffee:51
return this.bean.setColor(new Buffer([rgb.r, rgb.g, rgb.b]), callback);
^
TypeError: Cannot read property 'setColor' of undefined
at BeanManager.changeLight (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/src/bean-manager.coffee:18:10)
at BeanManager.changeLight (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/src/bean-manager.coffee:1:1)
at Connector.changeLight (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/src/index.coffee:13:11)
at Connector.changeLight (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/src/index.coffee:1:1)
at ChangeLight.do (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/jobs/change-light/job.coffee:12:16)
at ChangeLight.do (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/jobs/change-light/job.coffee:1:1)
at Object.action (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/jobs/change-light/action.coffee:5:3)
at MessageHandler.onMessage (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/meshblu-connector-runner/src/message-handler.coffee:21:9)
at MessageHandler.onMessage (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/meshblu-connector-runner/src/message-handler.coffee:1:1)
at Connection.<anonymous> (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/meshblu-connector-runner/src/runner.coffee:46:25)
at emitOne (events.js:90:13)
at Connection.emit (events.js:182:7)
at Connection._handleAckRequest (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/meshblu/lib/Connection.js:190:12)
at Socket.<anonymous> (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/meshblu/lib/Connection.js:147:12)
at Socket.Emitter.emit (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/component-emitter/index.js:131:20)
at Socket.onevent (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/socket.io-client/lib/socket.js:263:10)
at Socket.onpacket (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/socket.io-client/lib/socket.js:221:12)
at Manager.<anonymous> (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/component-bind/index.js:21:15)
at Manager.Emitter.emit (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/component-emitter/index.js:131:20)
at Manager.ondecoded (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/socket.io-client/lib/manager.js:333:8)
at Decoder.<anonymous> (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/component-bind/index.js:21:15)
at Decoder.Emitter.emit (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/component-emitter/index.js:131:20)
at Decoder.add (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/socket.io-parser/index.js:247:12)
at Manager.ondata (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/socket.io-client/lib/manager.js:323:16)
at Socket.<anonymous> (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/component-bind/index.js:21:15)
at Socket.Emitter.emit (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/component-emitter/index.js:131:20)
at Socket.onPacket (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/engine.io-client/lib/socket.js:441:14)
at WS.<anonymous> (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/engine.io-client/lib/socket.js:258:10)
at WS.Emitter.emit (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/component-emitter/index.js:131:20)
at WS.Transport.onPacket (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/engine.io-client/lib/transport.js:143:8)
at WS.Transport.onData (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/engine.io-client/lib/transport.js:135:8)
at WebSocket.ws.onmessage (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/engine.io-client/lib/transports/websocket.js:132:10)
at WebSocket.onMessage (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/WebSocket.js:418:14)
at emitTwo (events.js:100:13)
at WebSocket.emit (events.js:185:7)
at Receiver.ontext (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/WebSocket.js:816:10)
at /Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/Receiver.js:477:18
at Receiver.applyExtensions (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/Receiver.js:364:5)
at /Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/Receiver.js:466:14
at Receiver.flush (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/Receiver.js:340:3)
at Receiver.opcodes.1.finish (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/Receiver.js:482:12)
at Receiver.expectHandler (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/Receiver.js:457:31)
at Receiver.add (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/Receiver.js:95:24)
at TLSSocket.realHandler (/Users/kdious/.octoblu/MeshbluConnectors/6304c325-c292-4177-a6d6-a9df17dd40e4/node_modules/ws/lib/WebSocket.js:800:20)
at emitOne (events.js:90:13)
at TLSSocket.emit (events.js:182:7)
at readableAddChunk (_stream_readable.js:147:16)
at TLSSocket.Readable.push (_stream_readable.js:111:10)
at TLSWrap.onread (net.js:523:20)

**Comment by royvandewater** [comment]
Weird, it makes me think it doesn't have a reference to the bean, but its clearly printing out information about the bean right before then. I'll have to take a look. I'm in Redmond this week, without a Bean. But I'll see if I can spot what the problem is later today, and if that fails, attempt to reproduce it when I'm back at our office on Monday.
